import type { Member } from "./types";

export const mockMembers: Member[] = [
  { id: "alex", name: "Alex", intro: "科技线推进型玩家，喜欢把复杂系统拆开研究。", interests: ["tech", "redstone", "development"], pace: "hardcore", availability: ["weekday_evening", "late_night"], duration: "very_long", groupSize: "duo", collaboration: "organizer", roles: ["planner", "technical"], communication: "voice", research: "self" },
  { id: "steve", name: "Steve", intro: "长线科技档爱好者，更喜欢稳定推进和固定小队。", interests: ["tech", "vanilla", "building"], pace: "steady", availability: ["weekday_evening", "weekend_evening"], duration: "long", groupSize: "small", collaboration: "divide", roles: ["technical", "builder"], communication: "optional", research: "together" },
  { id: "creeper", name: "Creeper", intro: "佛系建筑党，喜欢在大服里慢慢做自己的项目。", interests: ["building", "vanilla", "social"], pace: "casual", availability: ["weekend_day", "weekend_evening"], duration: "long", groupSize: "community", collaboration: "independent", roles: ["builder", "gatherer"], communication: "text", research: "casual" },
  { id: "redstone", name: "RedstoneCat", intro: "红石和自动化玩家，喜欢两三个人一起解决问题。", interests: ["redstone", "tech", "vanilla"], pace: "steady", availability: ["weekday_evening", "late_night"], duration: "long", groupSize: "small", collaboration: "together", roles: ["technical", "planner"], communication: "optional", research: "self" },
  { id: "builder", name: "MossBuilder", intro: "建筑主力，喜欢长期服务器和公共建设。", interests: ["building", "vanilla", "adventure"], pace: "steady", availability: ["weekend_day", "weekend_evening"], duration: "very_long", groupSize: "small", collaboration: "divide", roles: ["builder", "organizer"], communication: "voice", research: "together" },
  { id: "witch", name: "WitchHat", intro: "魔法与冒险整合包爱好者，偏小队共同探索。", interests: ["magic", "adventure", "tech"], pace: "casual", availability: ["weekday_evening", "weekend_evening"], duration: "medium", groupSize: "small", collaboration: "together", roles: ["explorer", "generalist"], communication: "optional", research: "together" },
  { id: "pvp", name: "PvPFox", intro: "小游戏和 PVP 高频玩家，喜欢短平快和热闹大服。", interests: ["pvp", "social", "vanilla"], pace: "hardcore", availability: ["weekday_evening", "weekend_evening"], duration: "short", groupSize: "community", collaboration: "together", roles: ["organizer", "generalist"], communication: "voice", research: "ask" },
  { id: "dev", name: "ByteSteve", intro: "服务端与 Mod 开发方向，偏技术协作和长期项目。", interests: ["development", "tech", "redstone"], pace: "steady", availability: ["late_night", "weekend_day"], duration: "very_long", groupSize: "duo", collaboration: "divide", roles: ["technical", "planner"], communication: "text", research: "self" },
  { id: "nomad", name: "EndNomad", intro: "探索党，喜欢新地图、新整合包和一起摸索。", interests: ["adventure", "magic", "vanilla"], pace: "adaptive", availability: ["weekend_day", "random"], duration: "medium", groupSize: "small", collaboration: "follower", roles: ["explorer", "gatherer"], communication: "optional", research: "together" },
  { id: "quiet", name: "QuietMiner", intro: "安静的资源玩家，更习惯文字沟通和各自推进。", interests: ["vanilla", "tech", "building"], pace: "casual", availability: ["late_night", "weekend_evening"], duration: "long", groupSize: "parallel", collaboration: "independent", roles: ["gatherer", "builder"], communication: "avoid", research: "self" },
  { id: "captain", name: "BlockCaptain", intro: "喜欢组织公共项目，把不同类型玩家拉到一起。", interests: ["vanilla", "building", "social"], pace: "adaptive", availability: ["weekday_evening", "weekend_day", "weekend_evening"], duration: "very_long", groupSize: "community", collaboration: "organizer", roles: ["organizer", "planner"], communication: "voice", research: "ask" },
  { id: "factory", name: "FactoryBee", intro: "自动化产线爱好者，偏稳定长线和明确分工。", interests: ["tech", "redstone", "building"], pace: "steady", availability: ["weekday_evening", "weekend_day"], duration: "very_long", groupSize: "small", collaboration: "divide", roles: ["technical", "gatherer"], communication: "optional", research: "self" }
];
