create table if not exists public.member_match_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile_version smallint not null default 2 check (profile_version >= 2),
  interest_scores jsonb not null default '{}'::jsonb,
  current_intents text[] not null default '{}'::text[],
  intent_updated_at timestamptz,
  availability_grid jsonb not null default '{}'::jsonb,
  availability_randomness smallint check (availability_randomness between 0 and 4),
  playstyle_preferences jsonb not null default '{}'::jsonb,
  role_preferences jsonb not null default '{}'::jsonb,
  boundary_preferences jsonb not null default '{}'::jsonb,
  learning_preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.member_match_profiles enable row level security;

drop policy if exists "Users can read their own V2 match profile" on public.member_match_profiles;
create policy "Users can read their own V2 match profile"
on public.member_match_profiles
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own V2 match profile" on public.member_match_profiles;
create policy "Users can create their own V2 match profile"
on public.member_match_profiles
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own V2 match profile" on public.member_match_profiles;
create policy "Users can update their own V2 match profile"
on public.member_match_profiles
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own V2 match profile" on public.member_match_profiles;
create policy "Users can delete their own V2 match profile"
on public.member_match_profiles
for delete
to authenticated
using ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.member_match_profiles to authenticated;

create table if not exists public.match_feedback (
  id bigint generated by default as identity primary key,
  viewer_user_id uuid not null references auth.users(id) on delete cascade,
  candidate_user_id uuid not null references auth.users(id) on delete cascade,
  feedback text check (feedback in ('positive', 'neutral', 'negative')),
  reason text,
  qq_copied boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.match_feedback enable row level security;

drop policy if exists "Users can read their own match feedback" on public.match_feedback;
create policy "Users can read their own match feedback"
on public.match_feedback
for select
to authenticated
using ((select auth.uid()) = viewer_user_id);

drop policy if exists "Users can create their own match feedback" on public.match_feedback;
create policy "Users can create their own match feedback"
on public.match_feedback
for insert
to authenticated
with check ((select auth.uid()) = viewer_user_id);

grant select, insert on public.match_feedback to authenticated;

create index if not exists match_feedback_viewer_created_idx
  on public.match_feedback (viewer_user_id, created_at desc);
create index if not exists member_match_profiles_updated_idx
  on public.member_match_profiles (updated_at desc);
